/**
 * Manter em sincronia com `pdv-inteligente-api/src/utils/normalizeFeature.ts`.
 *
 * Normaliza identificadores de feature para o formato canônico:
 * MODULO.ENTIDADE_ACAO (uppercase, entidade no singular).
 * Valores canônicos devem existir em `FEATURE_MASTER_MAP`.
 */
const FEATURE_NORMALIZATION_MAP: Record<string, string> = {
  // --- Dashboard ---
  DASHBOARD: 'DASHBOARD.VIEW',
  // Identidade explícita — evita que o bloco geral gere DASHBOARD.VIEW_VIEW
  'DASHBOARD.VIEW': 'DASHBOARD.VIEW',
  'DASHBOARD.FOOD_VIEW': 'DASHBOARD.FOOD_VIEW',
  // Safety alias para dados já salvos com código malformado
  'DASHBOARD.VIEW_VIEW': 'DASHBOARD.VIEW',

  // --- IA ---
  IA: 'IA.INSIGHT_VIEW',
  // Sub-módulos legados (plural) e variantes incorretas geradas pelo frontend
  'IA.INSIGHTS': 'IA.INSIGHT_VIEW',
  'IA.INSIGHT': 'IA.INSIGHT_VIEW',
  'IA.INSIGHTS_VIEW': 'IA.INSIGHT_VIEW',
  'IA.ALERTAS': 'IA.ALERT_VIEW',
  'IA.ALERTA': 'IA.ALERT_VIEW',
  'IA.ALERTAS_VIEW': 'IA.ALERT_VIEW',
  'IA.OPORTUNIDADES': 'IA.OPPORTUNITY_VIEW',
  'IA.OPORTUNIDADE': 'IA.OPPORTUNITY_VIEW',
  'IA.OPORTUNIDADES_VIEW': 'IA.OPPORTUNITY_VIEW',

  // --- Estrutura (legado plural / sem sufixo) ---
  'ESTRUTURA.PRODUTOS': 'ESTRUTURA.PRODUTO_VIEW',
  'ESTRUTURA.PRODUTO': 'ESTRUTURA.PRODUTO_VIEW',
  'ESTRUTURA.PESSOAS': 'ESTRUTURA.PESSOA_VIEW',
  'ESTRUTURA.PESSOA': 'ESTRUTURA.PESSOA_VIEW',
  'ESTRUTURA.CATEGORIAS': 'ESTRUTURA.CATEGORIA_VIEW',
  'ESTRUTURA.CATEGORIA': 'ESTRUTURA.CATEGORIA_VIEW',
  'ESTRUTURA.EMBALAGENS': 'ESTRUTURA.EMBALAGEM_VIEW',
  'ESTRUTURA.EMBALAGEM': 'ESTRUTURA.EMBALAGEM_VIEW',
  'ESTRUTURA.EQUIPES': 'ESTRUTURA.EQUIPE_VIEW',
  'ESTRUTURA.EQUIPE': 'ESTRUTURA.EQUIPE_VIEW',
  'ESTRUTURA.PERMISSOES': 'ESTRUTURA.PERMISSAO_VIEW',
  'ESTRUTURA.PERMISSAO': 'ESTRUTURA.PERMISSAO_VIEW',
  'ESTRUTURA.LOJA': 'ESTRUTURA.LOJA_VIEW',
  'ESTRUTURA.MINHA_LOJA': 'ESTRUTURA.LOJA_VIEW',
  'ESTRUTURA.ETIQUETAS': 'ESTRUTURA.ETIQUETA_VIEW',
  'ESTRUTURA.ETIQUETA': 'ESTRUTURA.ETIQUETA_VIEW',
  'ESTRUTURA.ESTACOES': 'ESTRUTURA.ESTACAO_VIEW',
  'ESTRUTURA.ESTACAO': 'ESTRUTURA.ESTACAO_VIEW',
  'ESTRUTURA.LOCAIS_COBRANCA': 'ESTRUTURA.LOCAL_COBRANCA_VIEW',
  'ESTRUTURA.LOCAL_COBRANCA': 'ESTRUTURA.LOCAL_COBRANCA_VIEW',
  'ESTRUTURA.CAIXAS_PDV': 'ESTRUTURA.CAIXA_PDV_VIEW',
  'ESTRUTURA.CAIXA_PDV': 'ESTRUTURA.CAIXA_PDV_VIEW',
  'ESTRUTURA.TEF': 'ESTRUTURA.TEF_VIEW',
  'ESTRUTURA.BALANCAS': 'ESTRUTURA.BALANCA_VIEW',
  'ESTRUTURA.BALANCA': 'ESTRUTURA.BALANCA_VIEW',

  // --- PDV ---
  'PDV.VAREJO': 'PDV.VENDA_VIEW',
  'PDV.VENDA': 'PDV.VENDA_VIEW',
  'PDV.AUTOATENDIMENTO': 'PDV.SELF_CHECKOUT_VIEW',
  'PDV.SELF': 'PDV.SELF_CHECKOUT_VIEW',
  'PDV.SELF_CHECKOUT': 'PDV.SELF_CHECKOUT_VIEW',
  'PDV.FOOD': 'PDV.FOOD_VIEW',

  // --- Food ---
  'FOOD_SERVICE.PDV': 'PDV.FOOD_VIEW',
  'FOOD_SERVICE.AUTOATENDIMENTO': 'FOOD_SERVICE.AUTOATENDIMENTO_VIEW',
  'FOOD_SERVICE.PEDIDOS': 'FOOD_SERVICE.DELIVERY_VIEW',
  'FOOD_SERVICE.CARDAPIOS': 'FOOD_SERVICE.CARDAPIO_VIEW',
  'FOOD_SERVICE.CARDAPIO': 'FOOD_SERVICE.CARDAPIO_VIEW',
  'FOOD_SERVICE.KDS': 'FOOD_SERVICE.KDS_VIEW',
  'FOOD_SERVICE.DELIVERY': 'FOOD_SERVICE.DELIVERY_VIEW',
  'FOOD_SERVICE.EXPEDICAO': 'FOOD_SERVICE.EXPEDICAO_VIEW',
  'FOOD_SERVICE.COMANDA_MOBILE': 'FOOD_SERVICE.COMANDA_MOBILE_VIEW',
  'FOOD_SERVICE.GARCOM': 'FOOD_SERVICE.MESAS_VIEW',
  'FOOD_SERVICE.MESAS': 'FOOD_SERVICE.MESAS_VIEW',
  'FOOD_SERVICE.IFOOD': 'FOOD_SERVICE.DELIVERY_VIEW',
  'FOOD_SERVICE.DASHBOARD': 'DASHBOARD.FOOD_VIEW',

  // --- Comercial ---
  'COMERCIAL.CAMPANHAS': 'COMERCIAL.CAMPAIGN_VIEW',
  'COMERCIAL.CAMPANHA': 'COMERCIAL.CAMPAIGN_VIEW',
  'COMERCIAL.LISTA_PRECO': 'COMERCIAL.LISTA_PRECO_VIEW',
  'COMERCIAL.LISTAS_PRECO': 'COMERCIAL.LISTA_PRECO_VIEW',
  'COMERCIAL.CARGA_BALANCA': 'COMERCIAL.CARGA_BALANCA_VIEW',
  'COMERCIAL.CARGA_BALANCAS': 'COMERCIAL.CARGA_BALANCA_VIEW',

  // --- Compras ---
  'COMPRAS.SOLICITACOES': 'COMPRAS.SOLICITACAO_VIEW',
  'COMPRAS.SOLICITACAO': 'COMPRAS.SOLICITACAO_VIEW',
  'COMPRAS.COTACOES': 'COMPRAS.COTACAO_VIEW',
  'COMPRAS.COTACAO': 'COMPRAS.COTACAO_VIEW',
  'COMPRAS.GER_COTACOES': 'COMPRAS.COTACAO_MANAGE_VIEW',
  'COMPRAS.APROVACAO': 'COMPRAS.APROVACAO_VIEW',
  'COMPRAS.PEDIDOS': 'COMPRAS.PEDIDO_VIEW',
  'COMPRAS.PEDIDO': 'COMPRAS.PEDIDO_VIEW',
  'COMPRAS.ACOMPANHAMENTO': 'COMPRAS.ACOMPANHAMENTO_VIEW',
  'COMPRAS.PEDIDOS_RECEBIMENTO': 'COMPRAS.RECEBIMENTO_ORDER_VIEW',
  'COMPRAS.RECEBIMENTO': 'COMPRAS.RECEBIMENTO_VIEW',
  'COMPRAS.DIVERGENCIAS': 'COMPRAS.DIVERGENCIA_VIEW',
  'COMPRAS.DIVERGENCIA': 'COMPRAS.DIVERGENCIA_VIEW',
  'COMPRAS.XML': 'COMPRAS.XML_VIEW',
  'COMPRAS.NOTAS_ENTRADA': 'COMPRAS.NOTA_ENTRADA_VIEW',
  'COMPRAS.NOTA_ENTRADA': 'COMPRAS.NOTA_ENTRADA_VIEW',
  'COMPRAS.AURYA': 'COMPRAS.AURYA_VIEW',

  // --- Estoque (módulo próprio com features canônicas ESTOQUE.*) ---
  'ESTOQUE.AURYA': 'ESTOQUE.INSIGHT_VIEW',
  'ESTOQUE.INTELIGENCIA': 'ESTOQUE.INSIGHT_VIEW',
  'ESTOQUE.GESTAO': 'ESTOQUE.GESTAO_VIEW',
  'ESTOQUE.INVENTARIO': 'ESTOQUE.INVENTARIO_VIEW',
  'ESTOQUE.BIPADOR': 'ESTOQUE.BIPADOR_VIEW',
  'ESTOQUE.LISTAS_PRECO': 'ESTOQUE.LISTA_PRECO_VIEW',
  'ESTOQUE.LISTA_PRECO': 'ESTOQUE.LISTA_PRECO_VIEW',
  'ESTOQUE.CARGA_BALANCAS': 'ESTOQUE.CARGA_BALANCA_VIEW',
  'ESTOQUE.CARGA_BALANCA': 'ESTOQUE.CARGA_BALANCA_VIEW',

  // --- WMS ---
  'WMS.RECEBIMENTO': 'WMS.DOCA_RECEBIMENTO_VIEW',
  'WMS.ARMAZENAGEM': 'WMS.PUTAWAY_VIEW',
  'WMS.ESTOQUE': 'WMS.ESTOQUE_VIEW',
  'WMS.MAPA': 'WMS.MAPA_VIEW',
  'WMS.AREAS': 'WMS.AREA_VIEW',
  'WMS.AREA': 'WMS.AREA_VIEW',
  'WMS.CAMARAS': 'WMS.AREA_VIEW',

  // --- Produção ---
  'PRODUCAO.ORDENS': 'PRODUCAO.ORDEM_VIEW',
  'PRODUCAO.ORDEM': 'PRODUCAO.ORDEM_VIEW',
  'PRODUCAO.BALANCA': 'PRODUCAO.BALANCA_VIEW',

  // --- Fiscal ---
  'FISCAL.PDV': 'NFE.PDV_NOTA_VIEW',
  'FISCAL.NFE': 'NFE.EMISSAO_VIEW',
  'FISCAL.MOTOR': 'NFE.MOTOR_VIEW',
  'FISCAL.CFOP': 'NFE.CFOP_VIEW',
  'NFE.EMISSAO': 'NFE.EMISSAO_VIEW',
  'NFE.PDV': 'NFE.PDV_NOTA_VIEW',

  // --- Financeiro ---
  'FINANCEIRO.TITULOS': 'FINANCEIRO.TITULO_VIEW',
  'FINANCEIRO.TITULO': 'FINANCEIRO.TITULO_VIEW',
  'FINANCEIRO.CONTAS_CAIXAS': 'FINANCEIRO.CONTA_VIEW',
  'FINANCEIRO.CONTA': 'FINANCEIRO.CONTA_VIEW',
  'FINANCEIRO.EXTRATO': 'FINANCEIRO.EXTRATO_VIEW',
  'FINANCEIRO.CHEQUES': 'FINANCEIRO.CHEQUE_VIEW',
  'FINANCEIRO.CHEQUE': 'FINANCEIRO.CHEQUE_VIEW',
  'FINANCEIRO.AURYA': 'FINANCEIRO.INSIGHT_VIEW',
  'FINANCEIRO.INSIGHT': 'FINANCEIRO.INSIGHT_VIEW',

  // --- Contábil ---
  'CONTABIL.AURYA': 'CONTABIL.INSIGHT_VIEW',
  'CONTABIL.INSIGHT': 'CONTABIL.INSIGHT_VIEW',
  'CONTABIL.DRE': 'CONTABIL.DRE_VIEW',
  'CONTABIL.PLANO_CONTAS': 'CONTABIL.PLANO_VIEW',
  'CONTABIL.PLANO': 'CONTABIL.PLANO_VIEW',
  'CONTABIL.RAZAO': 'CONTABIL.RAZAO_VIEW',
  'CONTABIL.LIVRO_RAZAO': 'CONTABIL.RAZAO_VIEW',
  'CONTABIL.CONCILIACAO': 'CONTABIL.CONCILIACAO_VIEW',
  'CONTABIL.FECHAMENTO': 'CONTABIL.FECHAMENTO_VIEW',

  // --- PDV turnos ---
  'PDV.TURNOS': 'PDV.TURNO_VIEW',
  'PDV.TURNO': 'PDV.TURNO_VIEW',

  // --- Vendas (gestão / documento fiscal) ---
  'VENDAS.GESTAO': 'VENDAS.GESTAO_VENDAS_VIEW',
  'VENDAS.GESTAO_VENDAS': 'VENDAS.GESTAO_VENDAS_VIEW',
  'VENDAS.GESTAO_VIEW': 'VENDAS.GESTAO_VENDAS_VIEW',
  'VENDAS.GESTAO_GERIR': 'VENDAS.GESTAO_VENDAS_GERIR',
  'VENDAS.GESTAO_VENDAS_GERIR': 'VENDAS.GESTAO_VENDAS_GERIR',

  // --- Tenant ---
  'ADMIN.CLIENTES': 'TENANT.CLIENT_VIEW',
};

/** Palavras-chave de ação que NÃO devem receber sufixo _VIEW automaticamente. */
const ACTION_KEYWORDS = new Set(['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'EDIT', 'EMIT', 'USE']);

export function normalizeFeature(feature: string): string {
  const raw = String(feature || '').trim().toUpperCase();
  if (!raw) return '';

  if (FEATURE_NORMALIZATION_MAP[raw]) {
    return FEATURE_NORMALIZATION_MAP[raw];
  }

  const parts = raw.split('.').filter(Boolean);
  if (parts.length >= 3) {
    return raw;
  }

  if (parts.length === 2 && !raw.endsWith('_VIEW') && !raw.endsWith('_CREATE') && !raw.endsWith('_EDIT') && !raw.endsWith('_DELETE')) {
    const [mod, ent] = parts;
    // Não adicionar _VIEW se a entidade já é uma palavra-chave de ação (ex: VIEW, CREATE)
    // Evita DASHBOARD.VIEW → DASHBOARD.VIEW_VIEW
    if (ent && !ent.includes('_') && !ACTION_KEYWORDS.has(ent)) {
      return `${mod}.${ent}_VIEW`;
    }
  }

  return raw;
}

export function normalizeFeatures(features: string[]): string[] {
  if (!Array.isArray(features)) return [];
  const normalized = features.map((f) => normalizeFeature(f)).filter(Boolean);
  return [...new Set(normalized)];
}
