/**
 * Alinhado ao catálogo RBAC do backend (`rbacPermissions.resolvePermission`).
 */
const LEGACY_PERMISSION_MAP: Record<string, string> = {
  VENDA_CRIAR: 'PDV_SELL',
  VENDA_CANCELAR: 'PDV_CANCEL',
  VENDA_GERIR: 'PDV_VIEW',
  VENDA_TEF_CONFIRMAR: 'PDV_SELL',
  FINANCEIRO_LANCAR: 'FINANCEIRO_CREATE',
  FINANCEIRO_ESTORNAR: 'FINANCEIRO_REVERSE',
  FINANCEIRO_GERIR_CAIXA: 'PDV_OPEN_CASH',
  ESTOQUE_BAIXAR: 'ESTOQUE_OUTPUT',
  ESTOQUE_AJUSTAR: 'ESTOQUE_ADJUST',
  ESTOQUE_GERIR: 'ESTOQUE_VIEW',
  FISCAL_EMITIR_NFE: 'FISCAL_NFE_EMIT',
  FISCAL_GERIR: 'FISCAL_VIEW',
  ADMIN_GERIR_USUARIOS: 'ADMIN_USER_VIEW',
  ADMIN_GERIR_PERMISSOES: 'ADMIN_PERMISSION_VIEW',
  DASHBOARD_ACESSAR: 'DASHBOARD_VIEW',
  RELATORIOS_ACESSAR: 'REPORT_VIEW',
  COMPRAS_SOLICITAR: 'COMPRAS_REQUEST_CREATE',
  COMPRAS_APROVAR: 'COMPRAS_APPROVE',
  COMPRAS_GERIR: 'COMPRAS_REQUEST_VIEW',
  COMPRAS_RECEBER: 'COMPRAS_RECEIVE',
};

export function resolvePermission(permission: string): string {
  const normalized = String(permission || '').trim().toUpperCase();
  return LEGACY_PERMISSION_MAP[normalized] ?? normalized;
}
